services:

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend.dockerfile
    container_name: servermonitor-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: sqlite:////data/monitoring.db
      LOG_PATH_SPEEDTEST: /data/speedtest.csv
      LOG_PATH_CONNECTIVITY: /data/connectivity.csv
      SERVER_HEALTH_API_TOKEN: ${SERVER_HEALTH_API_TOKEN}
    volumes:
      - /mnt/media/monitoring/data:/data
    networks:
      - proxy-network

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.dockerfile
    container_name: servermonitor-frontend
    restart: unless-stopped
    networks:
      - proxy-network
    depends_on:
      - backend

networks:
  proxy-network:
    external: true
