"""initial schema

Revision ID: 611b4ddf7c6d
Revises: 
Create Date: 2026-03-10 12:47:04.281156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611b4ddf7c6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectivity_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectivity_checks_id'), 'connectivity_checks', ['id'], unique=False)
    op.create_index(op.f('ix_connectivity_checks_timestamp'), 'connectivity_checks', ['timestamp'], unique=False)
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('avg_download_mbps', sa.Float(), nullable=True),
    sa.Column('min_download_mbps', sa.Float(), nullable=True),
    sa.Column('avg_upload_mbps', sa.Float(), nullable=True),
    sa.Column('min_upload_mbps', sa.Float(), nullable=True),
    sa.Column('avg_ping', sa.Float(), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=True),
    sa.Column('successful_tests', sa.Integer(), nullable=True),
    sa.Column('failed_tests', sa.Integer(), nullable=True),
    sa.Column('degraded_count', sa.Integer(), nullable=True),
    sa.Column('degraded_total_minutes', sa.Integer(), nullable=True),
    sa.Column('total_checks', sa.Integer(), nullable=True),
    sa.Column('online_checks', sa.Integer(), nullable=True),
    sa.Column('offline_checks', sa.Integer(), nullable=True),
    sa.Column('outage_count', sa.Integer(), nullable=True),
    sa.Column('outage_total_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_summaries_id'), 'daily_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_daily_summaries_period_date'), 'daily_summaries', ['period_date'], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('speedtest_failures',
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('server_name', sa.String(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speedtest_failures_id'), 'speedtest_failures', ['id'], unique=False)
    op.create_index(op.f('ix_speedtest_failures_timestamp'), 'speedtest_failures', ['timestamp'], unique=False)
    op.create_table('speedtest_results',
    sa.Column('ping', sa.Float(), nullable=False),
    sa.Column('download_mbps', sa.Float(), nullable=False),
    sa.Column('upload_mbps', sa.Float(), nullable=False),
    sa.Column('performance_status', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('server_name', sa.String(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speedtest_results_id'), 'speedtest_results', ['id'], unique=False)
    op.create_index(op.f('ix_speedtest_results_timestamp'), 'speedtest_results', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speedtest_results_timestamp'), table_name='speedtest_results')
    op.drop_index(op.f('ix_speedtest_results_id'), table_name='speedtest_results')
    op.drop_table('speedtest_results')
    op.drop_index(op.f('ix_speedtest_failures_timestamp'), table_name='speedtest_failures')
    op.drop_index(op.f('ix_speedtest_failures_id'), table_name='speedtest_failures')
    op.drop_table('speedtest_failures')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_daily_summaries_period_date'), table_name='daily_summaries')
    op.drop_index(op.f('ix_daily_summaries_id'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_index(op.f('ix_connectivity_checks_timestamp'), table_name='connectivity_checks')
    op.drop_index(op.f('ix_connectivity_checks_id'), table_name='connectivity_checks')
    op.drop_table('connectivity_checks')
    # ### end Alembic commands ###
