"""add server health

Revision ID: 9dd2a7aebe1e
Revises: 611b4ddf7c6d
Create Date: 2026-08-27 11:28:03.503069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd2a7aebe1e'
down_revision: Union[str, Sequence[str], None] = '611b4ddf7c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('load_1', sa.Float(), nullable=True),
    sa.Column('load_5', sa.Float(), nullable=True),
    sa.Column('load_15', sa.Float(), nullable=True),
    sa.Column('memory_total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('memory_available_bytes', sa.BigInteger(), nullable=True),
    sa.Column('swap_total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('swap_used_bytes', sa.BigInteger(), nullable=True),
    sa.Column('cpu_package_temp_c', sa.Float(), nullable=True),
    sa.Column('cpu_core0_temp_c', sa.Float(), nullable=True),
    sa.Column('cpu_core1_temp_c', sa.Float(), nullable=True),
    sa.Column('disk_read_bytes', sa.BigInteger(), nullable=True),
    sa.Column('disk_write_bytes', sa.BigInteger(), nullable=True),
    sa.Column('disk_read_iops', sa.Float(), nullable=True),
    sa.Column('disk_write_iops', sa.Float(), nullable=True),
    sa.Column('disk_util_percent', sa.Float(), nullable=True),
    sa.Column('network_rx_bytes', sa.BigInteger(), nullable=True),
    sa.Column('network_tx_bytes', sa.BigInteger(), nullable=True),
    sa.Column('network_rx_errors', sa.BigInteger(), nullable=True),
    sa.Column('network_tx_errors', sa.BigInteger(), nullable=True),
    sa.Column('network_rx_drops', sa.BigInteger(), nullable=True),
    sa.Column('network_tx_drops', sa.BigInteger(), nullable=True),
    sa.Column('uptime_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_health_id'), 'server_health', ['id'], unique=False)
    op.create_index(op.f('ix_server_health_timestamp'), 'server_health', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_health_timestamp'), table_name='server_health')
    op.drop_index(op.f('ix_server_health_id'), table_name='server_health')
    op.drop_table('server_health')
    # ### end Alembic commands ###
