"""add server health SMART devices

Revision ID: ee6e705c11fa
Revises: be2aadc47bd9
Create Date: 2026-08-28 08:18:14.206501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6e705c11fa'
down_revision: Union[str, Sequence[str], None] = 'be2aadc47bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_health_smart_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_health_id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=512), nullable=False),
    sa.Column('model', sa.String(length=512), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('reallocated_sectors', sa.BigInteger(), nullable=True),
    sa.Column('pending_sectors', sa.BigInteger(), nullable=True),
    sa.Column('uncorrectable_sectors', sa.BigInteger(), nullable=True),
    sa.Column('power_on_hours', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['server_health_id'], ['server_health.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_health_smart_devices_id'), 'server_health_smart_devices', ['id'], unique=False)
    op.create_index(op.f('ix_server_health_smart_devices_server_health_id'), 'server_health_smart_devices', ['server_health_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_health_smart_devices_server_health_id'), table_name='server_health_smart_devices')
    op.drop_index(op.f('ix_server_health_smart_devices_id'), table_name='server_health_smart_devices')
    op.drop_table('server_health_smart_devices')
    # ### end Alembic commands ###
